Update for API 4.0.0-BETA8 and 4.0.0-BETA9
Muqsit/InvMenu pull request #159
Opened 2021-10-27 07:03 UTC by NgLamVN

# Introduction
* This PR contain some update related to newest protocol changes in BedrockProtocol for PocketMine-MP 4.0.0-BETA6 and 4.0.0-BETA7

2021-10-27 22:20 UTC, Muqsit requested changes

2021-10-27 22:20 UTC, Muqsit commented on src/muqsit/invmenu/type/graphic/BlockActorInvMenuGraphic.php
> +		$player->getNetworkSession()->sendDataPacket(BlockActorDataPacket::create(BlockPosition::fromVector3(new Vector3($this->position->x, $this->position->y, $this->position->z)), new CacheableNbt($this
This can be replaced with `BlockPosition::fromVector3($this->position)`

2021-10-27 22:20 UTC, Muqsit commented on src/muqsit/invmenu/type/graphic/network/BlockInvMenuGraphicNetworkTranslator.php
> +		$packet->blockPosition = BlockPosition::fromVector3($pos->asVector3());
Hm I'm not sure why I `(int)`-casted coordinates.. it might have been for the sake of PHPStan. However, the equivalent of this would be `new BlockPosition((int) $pos->x, (int) $pos->y, (int) $pos->z)`, or better.. `BlockPosition::fromPosition($pos)` since `$pos` is Vector3 already.

2021-10-30 04:04 UTC, KygekDev commented on virion.yml
> +  - 4.0.0-BETA9
Unfortunately the `api` field in `plugin.yml` and `virion.yml` didn't work with `-BETA` versions.

What I mean is I'm currently using https://github.com/NgLamVN/InvMenu/tree/73eb7925311e0b2b0bc26d90092a9875f9680d4e with DEVirion in PocketMine-MP version 4.0.0-BETA8 however the virion still loads fine.

2021-10-30 17:26 UTC, Muqsit requested changes

2021-10-30 17:26 UTC, Muqsit commented on src/muqsit/invmenu/InvMenuEventHandler.php
> -<?php
It looks like this file replaced all line breaks from UNIX format to DOS format.
If you edited this file on windows, you can use a windows-equivalent of linux's `dos2unix` tool, or alternatively find `\r\n` and replace with `\n`.

2021-11-02 14:08 UTC, closed without merging